# -*- coding: utf-8 -*-
"""DataAugmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5ZxE0crkuYHXlak04_4YqXgJXVTNEb5
"""

!pip install albumentations opencv-python matplotlib

from google.colab import files
uploaded = files.upload()

import cv2
import albumentations as A
import matplotlib.pyplot as plt

# Load image
image_path = list(uploaded.keys())[0]
image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Define multiple augmentations
transform = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.RandomBrightnessContrast(p=0.5),
    A.Rotate(limit=30, p=0.5),
    A.GaussianBlur(p=0.3),
])

# Generate augmented images
augmented_images = [image]

for i in range(5):
    augmented = transform(image=image)
    augmented_images.append(augmented["image"])

# Plot grid
plt.figure(figsize=(12, 6))

for i, img in enumerate(augmented_images):
    plt.subplot(2, 3, i+1)
    if i == 0:
        plt.title("Original")
    else:
        plt.title(f"Augmented {i}")
    plt.imshow(img)
    plt.axis("off")

plt.tight_layout()
plt.savefig("augmentation_grid.png")
plt.show()

files.download("augmentation_grid.png")